package com.fateczl.muttley.auditoria;

public enum AcaoAuditoria {
    CRIADO, ALTERADO, DELETADO,
    CHECK_IN, PRESENCA_VALIDADA,
    CERTIFICADO_EMITIDO, MEDALHA_CONCEDIDA,
    INSCRICAO_CRIADA, INSCRICAO_CANCELADA, STATUS_ATUALIZADO
}
